apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: cbpautomation/python-hello-world-docker
          version: 1.2.0 
          url: index.docker.io/cbpautomation/python-hello-world-docker:0.0.181
          digest: index.docker.io/cbpautomation/python-hello-world-docker:0.0.181
          target-environment: PREPROD
