apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: 0.0.0
      env:
        type: string
        default: PREPROD
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: cbpautomation/python-hello-world-docker
          version: ${inputs.version}
          url: docker.io/cbpautomation/python-hello-world-docker:${inputs.version}
          digest: sha256:102f6f3d863fcd801815e527be029cb191059416616f3581b55e20585f4a7dec
          target-environment: ${inputs.env}
